application: community-tools
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /test
  static_dir: test
- url: /news.*
  script: news.app
- url: /twitter.*
  script: twitter.app
- url: /buses.*
  script: buses.app
- url: /planning.*
  script: planning.app
- url: /weather.*
  script: weather.app